{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    release: {{ .Release.Name }}
spec:
  type: {{ default "NodePort" .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    {{- with .Values.backend.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  selector:
    app: backend
    release: {{ .Release.Name }}
{{- end }}
