mongodb:
  enabled: true
  image: mongo:7
  replicas: 1
  database: ToDoAppDb
  service:
    port: 27017

backend:
  enabled: true
  image: ghcr.io/andreasvilhelmsson/todo-backend:20251007
  replicas: 2
  service:
    type: NodePort
    port: 80
    targetPort: 8080
    nodePort: null
  config:
    mongoConnectionString: "mongodb://mongodb:27017"
    mongoDatabase: "ToDoAppDb"
    mongoCollection: "ToDoItems"

frontend:
  enabled: true
  image: ghcr.io/andreasvilhelmsson/todo-frontend:20251008
  replicas: 2
  service:
    type: LoadBalancer
    port: 80
  config:
    apiUrl: ""

imagePullSecrets:
  - ghcr-credentials
